# Ustawienia builda
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Wersje (Fabric 1.21.1 - podmien jesli uzywasz innej wersji 1.21.x)
minecraft_version=26.2
loader_version=0.19.5

# Mod
mod_version=1.1.1
maven_group=com.pikselhud
archives_base_name=pikselhud

# Zaleznosci
fabric_version=0.159.0+26.2
